#!/bin/bash




export PATH=$PATH:$(cd $(dirname "$0") && pwd -P)
export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.6/bin

cd $(cd $(dirname "$0") && pwd -P)
pwd


PLATFORM=mac64
VERSION=$(curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
curl -o chromedriver.zip http://chromedriver.storage.googleapis.com/$VERSION/chromedriver_$PLATFORM.zip
unzip chromedriver.zip
rm chromedriver.zip


pip3 install requests
pip3 install selenium
pip3 install bs4
pip3 install eventlet

python3 berlin_staats.py
python3 berlin_image.py
